baseURL  = "https://ayahramahi.github.io/"
languageCode  = "en-us"
title  = "Ayah Al-Ramahi"
theme  = "PaperMod"

enableRobotsTXT  =  false
buildDrafts  =  false
buildFuture  = false
buildExpired  = false

defaultTheme = "light"

[minify]
    disableXML  =  true
    minifyOutput  = true

[assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

[params]

    [params.profileMode]
        enabled = true
        title = "Ayah Al-Ramahi"
        subtitle = "Engineer | Learner | Dreamer"
        imageUrl = "/ar-500.png"
        imageTitle = "logo"
        imageWidth = 120.0
        imageHeight = 120.0

    [[params.socialIcons]]
        name = "GitHub"
        url = "https://github.com/AyahRamahi"

    [[params.socialIcons]]
        name = "LinkedIn"
        url = "https://linkedin.com/ayahRamahi"

    [[params.socialIcons]]
        name = "Email"
        url = "mailto:ayah_alramahi@yahoo.com"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10.0

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 20.0
    
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 30.0